#!/bin/sh
export GEM_HOME=~/.gem
export PATH=~/bin:~/go/bin:~/.gem/bin:~/.local/bin:~/.composer/vendor/bin:$PATH


alias php="php -c ~/php.ini"

# set vim as default editor
export EDITOR=/usr/bin/vim

# bash options
set 'bind bell-style none'
set show-all-if-ambiguous on
set completion-ignore-case on
alias tmux='TERM=xterm-256color; tmux -2'
export PROMPT_DIRTRIM=2
export PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h:\[\033[01;34m\]\w\[\033[00m\]\$ '
source $HOME/.local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh

if [ -f ~/.bash_jump ]; then . ~/.bash_jump; fi

export GOPATH=/home/lang/workspace/go
export PATH=$GOPATH/bin:$PATH

export COMPOSER_HOME=$HOME/.composer
